// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdButton: typeof import('./../components/AdButton/index.vue')['default']
    Awarded: typeof import('./../components/NewbiePack/components/Awarded.vue')['default']
    BackIcon: typeof import('./../components/BackIcon/index.vue')['default']
    ChangeLang: typeof import('./../components/ChangeLang/index.vue')['default']
    DailyCheck: typeof import('./../components/NewbiePack/components/DailyCheck.vue')['default']
    IIcon: typeof import('./../components/IIcon/index.vue')['default']
    Init: typeof import('./../components/NewbiePack/components/Init.vue')['default']
    InitPage: typeof import('./../components/NewbiePack/components/InitPage.vue')['default']
    NavBar: typeof import('./../components/NavBar/index.vue')['default']
    NewbiePack: typeof import('./../components/NewbiePack/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShadowBorderBox: typeof import('./../components/ShadowBorderBox/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Tabbar: typeof import('./../components/Tabbar/index.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCircle: typeof import('vant/es')['Circle']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanSpace: typeof import('vant/es')['Space']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
